services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:81"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    container_name: nginx_app
    depends_on:
      - php
    networks:
      - app-network

  php:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - GROUP_APP=${GROUP_APP}
        - USER_APP=${USER_APP}
    ports:
      - "9000:9000"
    container_name: php_app
    environment:
      - GROUP_APP=${GROUP_APP}
      - USER_APP=${USER_APP}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
