services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - GROUP_APP=${GROUP_APP}
        - USER_APP=${USER_APP}
    ports:
      - "8076:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./../app/:/var/www/html
    container_name: nginx_app
    environment:
      - GROUP_APP=${GROUP_APP}
      - USER_APP=${USER_APP}
    depends_on:
      - php
    networks:
      - app-network

  php:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - GROUP_APP=${GROUP_APP}
        - USER_APP=${USER_APP}
    ports:
      - "9003:9003"
    container_name: php_app
    volumes:
      - ./../app/backend:/var/www/html/backend
    environment:
      - GROUP_APP=${GROUP_APP}
      - USER_APP=${USER_APP}
    networks:
      - app-network
  npm:
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        - GROUP_APP=${GROUP_APP}
        - USER_APP=${USER_APP}
    volumes:
      - ./../app/frontend:/var/www/html
    working_dir: /var/www/html
    container_name: npm_app
    command: tail -f /dev/null

networks:
  app-network:
    driver: bridge
